version: 2
project_name: kivtz
builds:
  - main: ./cmd/kivtz
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_arm64
      - linux_amd64
    ldflags:
      - -s -w
      - -X main.version=snapshot
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "kivtz_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  disable: true
