version: 2
project_name: kivtz
builds:
  - main: ./cmd/kivtz
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Tag}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "kivtz_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

release:
  github:
    owner: airbugg
    name: kivtz

changelog:
  disable: true
